### ISSUE TITLE
主题安装后hexo s报错是怎么回事啊

### ISSUE THREAD

**Issue by zlxFTH** [fooying/hexo-theme-xoxo-plus#4]
rt

**Comment by zlxFTH** [comment]
安装了hexo-reading-time还是有问题

**Comment by zlxFTH** [comment]
安装了hexo-reading-time还是有问题

**Comment by ghost** [comment]
##### 是这个错误🐴？
```
Unhandled rejection ReferenceError: /Users/xfei/Blog/tlcy_github_io/themes/hexo-theme-xoxo-plus/layout/layout.ejs:8
```

**Comment by shuhaoc** [comment]
> ##### 是这个错误🐴？
> ```
> Unhandled rejection ReferenceError: /Users/xfei/Blog/tlcy_github_io/themes/hexo-theme-xoxo-plus/layout/layout.ejs:8
> ```

+1

**Comment by zlxFTH** [comment]
> ##### 是这个错误🐴？
> ```
> Unhandled rejection ReferenceError: /Users/xfei/Blog/tlcy_github_io/themes/hexo-theme-xoxo-plus/layout/layout.ejs:8
> ```

是的

**Comment by zlxFTH** [comment]
怎么办啊

**Comment by imelonkid** [comment]
一样的问题

**Comment by imelonkid** [comment]
感觉这个主题作者不在维护了

**Comment by fooying** [comment]
有更详细的报错信息吗？

**Comment by fooying** [comment]
如果报错信息是
```
Unhandled rejection ReferenceError: /Volumes/fooying/dev/test/themes/hexo-theme-xoxo-plus/layout/layout.ejs:8
    6| <body>
    7|   <div class="nav-container">
 >> 8|     <%-partial('partials/nav')%>
    9|   </div>
    10|
    11|   <div class="container" id="content-outer">

/Volumes/fooying/dev/test/themes/hexo-theme-xoxo-plus/layout/partials/nav.ejs:11
    9|   <ul class="pure-menu-list clearfix">
    10|       <% Object.keys(theme.menu).forEach(function(key) { %>
 >> 11|           <% if (_.isPlainObject(theme.menu[key])) { %>
    12|             <% if (_.indexOf(Object.values(theme.menu[key]), '/'+page.path.split('/')[0]) != -1) { %>
    13|               <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover actived">
    14|             <% } else { %>

_ is not defined
```
主要是hexo更新新版本后，有一些库没有默认引用了，改为了原生JS操作，解决方案：
修改模板目录下文件：layout/partials/nav.ejs
```
11行 <% if (Object.prototype.toString.call(theme.menu[key]) === '[object Object]') { %>
12行 <% if (Object.values(theme.menu[key]).indexOf('/'+page.path.split('/')[0]) != -1) { %>
```

已将fix提交到仓库，更新模板也可以

**Comment by imelonkid** [comment]
> 如果报错信息是
> 
> ```
> Unhandled rejection ReferenceError: /Volumes/fooying/dev/test/themes/hexo-theme-xoxo-plus/layout/layout.ejs:8
>     6| <body>
>     7|   <div class="nav-container">
>  >> 8|     <%-partial('partials/nav')%>
>     9|   </div>
>     10|
>     11|   <div class="container" id="content-outer">
> 
> /Volumes/fooying/dev/test/themes/hexo-theme-xoxo-plus/layout/partials/nav.ejs:11
>     9|   <ul class="pure-menu-list clearfix">
>     10|       <% Object.keys(theme.menu).forEach(function(key) { %>
>  >> 11|           <% if (_.isPlainObject(theme.menu[key])) { %>
>     12|             <% if (_.indexOf(Object.values(theme.menu[key]), '/'+page.path.split('/')[0]) != -1) { %>
>     13|               <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover actived">
>     14|             <% } else { %>
> 
> _ is not defined
> ```
> 
> 主要是hexo更新新版本后，有一些库没有默认引用了，改为了原生JS操作，解决方案： 修改模板目录下文件：layout/partials/nav.ejs
> 
> ```
> 11行 <% if (Object.prototype.toString.call(theme.menu[key]) === '[object Object]') { %>
> 12行 <% if (Object.values(theme.menu[key]).indexOf('/'+page.path.split('/')[0]) != -1) { %>
> ```
> 
> 已将fix提交到仓库，更新模板也可以

点赞，我今天试试

**Comment by imelonkid** [comment]
主页面可以进来了，但是点文章详情的时候报错了
`
Unhandled rejection ReferenceError: /Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:28
    26|     </span>
    27|       <span class="slash">/</span>
 >> 28|       <span class="read">阅读耗时 <%=readingTime(page.content, '分钟') %></span>
    29|     </header>
    30| 
    31|     <div class="post-content">

readingTime is not defined
    at eval (/Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:34:7)
    at post (/Users/melonkid/Workspace/myself/melon-blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Unhandled rejection ReferenceError: /Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:28
    26|     </span>
    27|       <span class="slash">/</span>
 >> 28|       <span class="read">阅读耗时 <%=readingTime(page.content, '分钟') %></span>
    29|     </header>
    30| 
    31|     <div class="post-content">

readingTime is not defined
    at eval (/Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:34:7)
    at post (/Users/melonkid/Workspace/myself/melon-blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

**Comment by imelonkid** [comment]
Unhandled rejection ReferenceError: /Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:28
    26|     </span>
    27|       <span class="slash">/</span>
 >> 28|       <span class="read">阅读耗时 <%=readingTime(page.content, '分钟') %></span>
    29|     </header>
    30| 
    31|     <div class="post-content">

readingTime is not defined
    at eval (/Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:34:7)
    at post (/Users/melonkid/Workspace/myself/melon-blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Unhandled rejection ReferenceError: /Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:28
    26|     </span>
    27|       <span class="slash">/</span>
 >> 28|       <span class="read">阅读耗时 <%=readingTime(page.content, '分钟') %></span>
    29|     </header>
    30| 
    31|     <div class="post-content">

readingTime is not defined
    at eval (/Users/melonkid/Workspace/myself/melon-blog/themes/hexo-theme-xoxo-plus/layout/post.ejs:34:7)
    at post (/Users/melonkid/Workspace/myself/melon-blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/melonkid/Workspace/myself/melon-blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/melonkid/Workspace/myself/melon-blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by fooying** [comment]
readingTime is not defined问题请先在模板目录下执行npm install 安装hexo-reading-time
